SELECT 
STUDNO,
NAME,
TO_CHAR(BIRTHDAY, 'YYYY-MM-DD')
FROM STUDENT
WHERE TO_CHAR(BIRTHDAY, 'MM')=(01);

SELECT 
EMPNO,
ENAME,
TO_CHAR(HIREDATE, 'YYYY/MM/DD')
FROM EMP
WHERE TO_CHAR(HIREDATE, 'MM') IN (01,02,03); 

SELECT * FROM table;
