CREATE TABLE T_MENU_12
(
    ME_ID NUMBER PRIMARY KEY,
    ME_NAME VARCHAR2(128) NOT NULL,
    ME_PRICE NUMBER(10),
    ME_TYPE VARCHAR2(64),
    ME_DATE DATE
);


INSERT INTO T_MENU_12
VALUES(1, '싸이버거', 6000, '완전식품', SYSDATE);
INSERT INTO T_MENU_12
VALUES(2, '콩나물비빔밥', 7000, '탄수화물', SYSDATE);
INSERT INTO T_MENU_12
VALUES(3, '닭가슴살', 3000, '단백질', SYSDATE);
INSERT INTO T_MENU_12
VALUES(4, '베트남쌀국수', 8000, '탄수화물', SYSDATE);
INSERT INTO T_MENU_12
VALUES(5, '라면', 2000, '밀가루', SYSDATE);

SELECT * FROM T_MENU_12;

UPDATE T_MENU_12
SET ME_PRICE = 8500
WHERE ME_ID = 4;

DELETE FROM T_MENU_12
WHERE ME_ID = 5;
commit;
