/*
1. 삭제하는 것은 똑같지만 TRUNC는 저장공간까지 지워 메모리를 확보한다.
*/

-- 2.

CREATE TABLE T_MEMBER_POINT
(
    ID NUMBER(6),
    순번 NUMBER(6),
    멤버ID VARCHAR2(24) NOT NULL,
    점수 NUMBER(3),
    채점일시 DATE DEFAULT SYSDATE,
    CONSTRAINT T_MEMBER_POINT_pk PRIMARY KEY(ID, 순번)
);

-- 3.

CREATE SEQUENCE T_MEMBER_POINT_PK_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
;

-- 4.

CREATE SEQUENCE T_MEMBER_POINT_TIMES_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
;

INSERT INTO T_MEMBER_POINT (ID, 순번, 멤버ID, 점수) VALUES
(
T_MEMBER_POINT_PK_SEQ.NEXTVAL, 
(SELECT NVL(MAX(순번), 0) FROM T_MEMBER_POINT
WHERE 멤버ID ='AB') + 1, 
'AB', 
95
);

SELECT * FROM T_MEMBER_POINT ;
